apiVersion: v1
kind: Service
metadata:
  name: voyage-flight-price-api
spec:
  type: LoadBalancer
  selector:
    app: voyage-flight-price-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
